In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup #vast lib for web scarpping
import numpy as np

In [2]:
#A header is added so that the server does not think a bot is trying to ping

headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page=1', headers=headers).text

In [3]:
soup=BeautifulSoup(webpage,'html.parser')

In [4]:
soup.find('h2').text.strip()

'Companies in India'

To Find Out Names of The Companies

In [5]:
company_list = soup.find_all('h2', class_= 'companyCardWrapper__companyName')

In [6]:
for i in company_list:
    print(i.text.strip())

TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Jio
Axis Bank
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTIMindtree
IBM

To Find Ratings of The Company

In [7]:
print(soup.find('div', class_= 'rating_text rating_text--md').text.strip())

3.3

In [8]:
# For all companies present on a single webpage
ratings_company = []
for i in soup.find_all('div', class_= 'rating_text rating_text--md'):
    print(i.text.strip())
    ratings_company.append(i.text.strip())

3.3
3.7
3.6
3.7
3.6
3.8
3.5
3.4
4.0
3.4
3.6
3.8
4.4
3.6
3.6
3.9
3.9
4.6
3.6
3.9

To Find Reviews of The Company

In [9]:
reviews_company = []

In [10]:
for i in soup.find_all('span', class_= 'companyCardWrapper__companyRatingCount'):
    temp = ''
    temp = i.text.strip()
    reviews_company.append(temp.strip("()"))
print(reviews_company)

['1.1L', '73.2k', '64.9k', '61.3k', '53.1k', '52.1k', '48.6k', '45.8k', '45.8k', '43.1k', '42.1k', '38.3k', '33.5k', '33k', '32.2k', '31.3k', '27.3k', '27k', '26.4k', '25.7k']

To Find Company Type & Headquarters

In [11]:
ctype = []
hq = []
temp1 = []

for i in soup.find_all('span', class_= 'companyCardWrapper__interLinking'):
    temp1.append(i.text.strip())

print(temp1)

['IT Services & Consulting | Bengaluru +441 other locations', 'IT Services & Consulting | Bengaluru +259 other locations', 'IT Services & Consulting | Hyderabad +373 other locations', 'IT Services & Consulting | Hyderabad +231 other locations', 'IT Services & Consulting | Bengaluru +180 other locations', 'Banking | Mumbai +1846 other locations', 'IT Services & Consulting | Bengaluru +243 other locations', 'IT Services & Consulting | Chennai +231 other locations', 'Banking | Mumbai +1442 other locations', 'IT Services & Consulting | Hyderabad +322 other locations', 'Analytics & KPO | Hyderabad +181 other locations', 'BPO | Mumbai +254 other locations', 'Telecom | Mumbai +1956 other locations', 'Banking | Mumbai +1517 other locations', 'BPO | Bengaluru +181 other locations', 'Internet | Bengaluru +515 other locations', 'Retail | Mumbai +1157 other locations', 'BPO | Noida +51 other locations', 'IT Services & Consulting | Bengaluru +144 other locations', 'IT Services & Consulting | Bengaluru +161 other locations']

In [12]:
for i in temp1:
    if '|' in i:
        a,b = i.split('|', 1)
        ctype.append(a.strip())
        hq.append(b.strip())

print(ctype)
print()
print(hq)

['IT Services & Consulting', 'IT Services & Consulting', 'IT Services & Consulting', 'IT Services & Consulting', 'IT Services & Consulting', 'Banking', 'IT Services & Consulting', 'IT Services & Consulting', 'Banking', 'IT Services & Consulting', 'Analytics & KPO', 'BPO', 'Telecom', 'Banking', 'BPO', 'Internet', 'Retail', 'BPO', 'IT Services & Consulting', 'IT Services & Consulting']

['Bengaluru +441 other locations', 'Bengaluru +259 other locations', 'Hyderabad +373 other locations', 'Hyderabad +231 other locations', 'Bengaluru +180 other locations', 'Mumbai +1846 other locations', 'Bengaluru +243 other locations', 'Chennai +231 other locations', 'Mumbai +1442 other locations', 'Hyderabad +322 other locations', 'Hyderabad +181 other locations', 'Mumbai +254 other locations', 'Mumbai +1956 other locations', 'Mumbai +1517 other locations', 'Bengaluru +181 other locations', 'Bengaluru +515 other locations', 'Mumbai +1157 other locations', 'Noida +51 other locations', 'Bengaluru +144 other locations', 'Bengaluru +161 other locations']

To Find Out the Positives of the Company

In [13]:
high_rate = []

high = soup.find('span', class_= 'companyCardWrapper__ratingHeader--high')
high_rate.append(high.find_parent('div').find_next_sibling('span').text.strip())

print(high_rate)

['Job Security']

In [14]:
low_rate = []

low = soup.find('span', class_= 'companyCardWrapper__ratingHeader--critical')
low_rate.append(low.find_parent('div').find_next_sibling('span').text.strip())

print(low_rate)

['Promotions, Salary, Work Satisfaction']

To Extract it All - Single Page

In [15]:
company = soup.find_all('div', class_= 'companyCardWrapper')

In [16]:
len(company)

20

In [17]:
name, ratings, reviews, ctype, hq, merits, demerits = [], [], [], [], [], [], []

for i in company:

    # for finding the name of the company
    name.append(i.find('h2', class_= 'companyCardWrapper__companyName').text.strip())

    # for finding the ratings of the company
    ratings.append(i.find('div', class_= 'rating_text rating_text--md').text.strip())

    # for finding the number of reviews of the company
    reviews.append(i.find('span', class_= 'companyCardWrapper__companyRatingCount').text.strip())

    # for finding the industry and headquarters of the company
    temp1=[]
    temp1.append(i.find('span', class_= 'companyCardWrapper__interLinking').text.strip())
    a,b = temp1[0].split('|', 1)
    ctype.append(a.strip())
    hq.append(b.strip())
    # temp2 = []
    # temp2.append(i.find('span', class_= 'companyCardWrapper__ratingValues').text.strip())

    # for finding the highly rated and most critically rated for of the company
    high_rate = []
    low_rate = []
    high = i.find('span', class_= 'companyCardWrapper__ratingHeader--high')
    if high:
        h_text = high.find_parent('div').find_next_sibling('span', class_= 'companyCardWrapper__ratingValues').text.strip()
        high_rate.append(h_text)
    else:
        high_rate.append(np.nan)
    merits.append(high_rate)
    low = i.find('span', class_= 'companyCardWrapper__ratingHeader--critical')
    if low:
        l_text = low.find_parent('div').find_next_sibling('span', class_= 'companyCardWrapper__ratingValues').text.strip()
        low_rate.append(l_text)
    else:
        low_rate.append(np.nan)
    demerits.append(low_rate)

Creating the data frame

In [18]:
d = {'name': name, 'rating': ratings, 'reviews': reviews, 'company_type' : ctype, 'headquarters' : hq, 'most_rated': merits, 'most_critised': demerits}

df = pd.DataFrame(d)

df

,name,rating,reviews,company_type,headquarters,most_rated,most_critised
0,TCS,3.3,(1.1L),IT Services & Consulting,Bengaluru +441 other locations,[Job Security],"[Promotions, Salary, Work Satisfaction]"
1,Accenture,3.7,(73.2k),IT Services & Consulting,Bengaluru +259 other locations,[nan],"[Promotions, Salary, Work Satisfaction]"
2,Wipro,3.6,(64.9k),IT Services & Consulting,Hyderabad +373 other locations,[nan],"[Promotions, Salary, Work Satisfaction]"
3,Cognizant,3.7,(61.3k),IT Services & Consulting,Hyderabad +231 other locations,[nan],"[Promotions, Salary, Work Satisfaction]"
4,Capgemini,3.6,(53.1k),IT Services & Consulting,Bengaluru +180 other locations,"[Work Life Balance, Job Security]","[Promotions, Salary, Work Satisfaction]"
5,HDFC Bank,3.8,(52.1k),Banking,Mumbai +1846 other locations,"[Job Security, Skill Development]","[Promotions, Salary]"
6,Infosys,3.5,(48.6k),IT Services & Consulting,Bengaluru +243 other locations,[Job Security],"[Promotions, Salary, Work Satisfaction]"
7,HCLTech,3.4,(45.8k),IT Services & Consulting,Chennai +231 other locations,[nan],"[Promotions, Salary, Work Satisfaction]"
8,ICICI Bank,4.0,(45.8k),Banking,Mumbai +1442 other locations,"[Job Security, Promotions, Skill Development]",[nan]
9,Tech Mahindra,3.4,(43.1k),IT Services & Consulting,Hyderabad +322 other locations,[nan],"[Promotions, Salary, Work Satisfaction]"
10,Genpact,3.6,(42.1k),Analytics & KPO,Hyderabad +181 other locations,[Job Security],"[Promotions, Salary, Work Satisfaction]"
11,TP,3.8,(38.3k),BPO,Mumbai +254 other locations,"[Work Life Balance, Job Security]",[nan]
12,Jio,4.4,(33.5k),Telecom,Mumbai +1956 other locations,"[Job Security, Skill Development, Company Cult...",[nan]
13,Axis Bank,3.6,(33k),Banking,Mumbai +1517 other locations,[nan],"[Promotions, Work Satisfaction, Company Culture]"
14,Concentrix Corporation,3.6,(32.2k),BPO,Bengaluru +181 other locations,[Job Security],"[Promotions, Salary, Work Satisfaction]"
15,Amazon,3.9,(31.3k),Internet,Bengaluru +515 other locations,"[Company Culture, Work Life Balance, Salary]",[Promotions]
16,Reliance Retail,3.9,(27.3k),Retail,Mumbai +1157 other locations,"[Job Security, Skill Development, Work Life Ba...",[Promotions]
17,iEnergizer,4.6,(27k),BPO,Noida +51 other locations,"[Salary, Company Culture, Work Life Balance]",[nan]
18,LTIMindtree,3.6,(26.4k),IT Services & Consulting,Bengaluru +144 other locations,[nan],"[Promotions, Salary, Work Satisfaction]"
19,IBM,3.9,(25.7k),IT Services & Consulting,Bengaluru +161 other locations,"[Work Life Balance, Company Culture, Job Secur...",[Promotions]

Creating the dataset by extracting the above company information from 500 pages

In [2]:
final = pd.DataFrame()
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}

for j in range(1, 501):
    webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page={}'.format(j), headers=headers).text
    soup=BeautifulSoup(webpage,'html.parser')
    company = soup.find_all('div', class_= 'companyCardWrapper')

    name, ratings, reviews, ctype, hq, merits, demerits = [], [], [], [], [], [], []

    for i in company:

        # for finding the name of the company
        try:
            name.append(i.find('h2', class_= 'companyCardWrapper__companyName').text.strip())
        except:
            name.append(np.nan)

        # for finding the ratings of the company
        try:
            ratings.append(i.find('div', class_= 'rating_text rating_text--md').text.strip())
        except:
            ratings.append(np.nan)

        # for finding the number of reviews of the company
        try:
            reviews.append(i.find('span', class_= 'companyCardWrapper__companyRatingCount').text.strip())
        except:
            reviews.append(np.nan)

        # for finding the industry and headquarters of the company
        try:
            temp1=[]
            temp1.append(i.find('span', class_= 'companyCardWrapper__interLinking').text.strip())
            a,b = temp1[0].split('|', 1)
            ctype.append(a.strip())
            hq.append(b.strip())
        except:
            ctype.append(np.nan)
            hq.append(np.nan)

        # for finding the highly rated and most critically rated for of the company
        try:
            high_rate = []
            low_rate = []
            high = i.find('span', class_= 'companyCardWrapper__ratingHeader--high')
            if high:
                h_text = high.find_parent('div').find_next_sibling('span', class_= 'companyCardWrapper__ratingValues').text.strip()
                high_rate.append(h_text)
            else:
                high_rate.append(np.nan)
            merits.append(high_rate)
            low = i.find('span', class_= 'companyCardWrapper__ratingHeader--critical')
            if low:
                l_text = low.find_parent('div').find_next_sibling('span', class_= 'companyCardWrapper__ratingValues').text.strip()
                low_rate.append(l_text)
            else:
                low_rate.append(np.nan)
            demerits.append(low_rate)
        except:
            continue

    df=pd.DataFrame({
        'Name' : name,
        'Rating' : ratings,
        'Reviews' : reviews,
        'Company_Type' : ctype,
        'Headquarters' : hq,
        'Highly Rated' : merits,
        'Most Critically Rated' : demerits
    })

    final = pd.concat([final, df], ignore_index=True)

    #Logging
    print('Data from page {} has been added in the dataset successfully'. format(j))

Data from page 1 has been added in the dataset successfully
Data from page 2 has been added in the dataset successfully
Data from page 3 has been added in the dataset successfully
Data from page 4 has been added in the dataset successfully
Data from page 5 has been added in the dataset successfully
Data from page 6 has been added in the dataset successfully
Data from page 7 has been added in the dataset successfully
Data from page 8 has been added in the dataset successfully
Data from page 9 has been added in the dataset successfully
Data from page 10 has been added in the dataset successfully
Data from page 11 has been added in the dataset successfully
Data from page 12 has been added in the dataset successfully
Data from page 13 has been added in the dataset successfully
Data from page 14 has been added in the dataset successfully
Data from page 15 has been added in the dataset successfully
Data from page 16 has been added in the dataset successfully
Data from page 17 has been added in the dataset successfully
Data from page 18 has been added in the dataset successfully
Data from page 19 has been added in the dataset successfully
Data from page 20 has been added in the dataset successfully
Data from page 21 has been added in the dataset successfully
Data from page 22 has been added in the dataset successfully
Data from page 23 has been added in the dataset successfully
Data from page 24 has been added in the dataset successfully
Data from page 25 has been added in the dataset successfully
Data from page 26 has been added in the dataset successfully
Data from page 27 has been added in the dataset successfully
Data from page 28 has been added in the dataset successfully
Data from page 29 has been added in the dataset successfully
Data from page 30 has been added in the dataset successfully
Data from page 31 has been added in the dataset successfully
Data from page 32 has been added in the dataset successfully
Data from page 33 has been added in the dataset successfully
Data from page 34 has been added in the dataset successfully
Data from page 35 has been added in the dataset successfully
Data from page 36 has been added in the dataset successfully
Data from page 37 has been added in the dataset successfully
Data from page 38 has been added in the dataset successfully
Data from page 39 has been added in the dataset successfully
Data from page 40 has been added in the dataset successfully
Data from page 41 has been added in the dataset successfully
Data from page 42 has been added in the dataset successfully
Data from page 43 has been added in the dataset successfully
Data from page 44 has been added in the dataset successfully
Data from page 45 has been added in the dataset successfully
Data from page 46 has been added in the dataset successfully
Data from page 47 has been added in the dataset successfully
Data from page 48 has been added in the dataset successfully
Data from page 49 has been added in the dataset successfully
Data from page 50 has been added in the dataset successfully
Data from page 51 has been added in the dataset successfully
Data from page 52 has been added in the dataset successfully
Data from page 53 has been added in the dataset successfully
Data from page 54 has been added in the dataset successfully
Data from page 55 has been added in the dataset successfully
Data from page 56 has been added in the dataset successfully
Data from page 57 has been added in the dataset successfully
Data from page 58 has been added in the dataset successfully
Data from page 59 has been added in the dataset successfully
Data from page 60 has been added in the dataset successfully
Data from page 61 has been added in the dataset successfully
Data from page 62 has been added in the dataset successfully
Data from page 63 has been added in the dataset successfully
Data from page 64 has been added in the dataset successfully
Data from page 65 has been added in the dataset successfully
Data from page 66 has been added in the dataset successfully
Data from page 67 has been added in the dataset successfully
Data from page 68 has been added in the dataset successfully
Data from page 69 has been added in the dataset successfully
Data from page 70 has been added in the dataset successfully
Data from page 71 has been added in the dataset successfully
Data from page 72 has been added in the dataset successfully
Data from page 73 has been added in the dataset successfully
Data from page 74 has been added in the dataset successfully
Data from page 75 has been added in the dataset successfully
Data from page 76 has been added in the dataset successfully
Data from page 77 has been added in the dataset successfully
Data from page 78 has been added in the dataset successfully
Data from page 79 has been added in the dataset successfully
Data from page 80 has been added in the dataset successfully
Data from page 81 has been added in the dataset successfully
Data from page 82 has been added in the dataset successfully
Data from page 83 has been added in the dataset successfully
Data from page 84 has been added in the dataset successfully
Data from page 85 has been added in the dataset successfully
Data from page 86 has been added in the dataset successfully
Data from page 87 has been added in the dataset successfully
Data from page 88 has been added in the dataset successfully
Data from page 89 has been added in the dataset successfully
Data from page 90 has been added in the dataset successfully
Data from page 91 has been added in the dataset successfully
Data from page 92 has been added in the dataset successfully
Data from page 93 has been added in the dataset successfully
Data from page 94 has been added in the dataset successfully
Data from page 95 has been added in the dataset successfully
Data from page 96 has been added in the dataset successfully
Data from page 97 has been added in the dataset successfully
Data from page 98 has been added in the dataset successfully
Data from page 99 has been added in the dataset successfully
Data from page 100 has been added in the dataset successfully
Data from page 101 has been added in the dataset successfully
Data from page 102 has been added in the dataset successfully
Data from page 103 has been added in the dataset successfully
Data from page 104 has been added in the dataset successfully
Data from page 105 has been added in the dataset successfully
Data from page 106 has been added in the dataset successfully
Data from page 107 has been added in the dataset successfully
Data from page 108 has been added in the dataset successfully
Data from page 109 has been added in the dataset successfully
Data from page 110 has been added in the dataset successfully
Data from page 111 has been added in the dataset successfully
Data from page 112 has been added in the dataset successfully
Data from page 113 has been added in the dataset successfully
Data from page 114 has been added in the dataset successfully
Data from page 115 has been added in the dataset successfully
Data from page 116 has been added in the dataset successfully
Data from page 117 has been added in the dataset successfully
Data from page 118 has been added in the dataset successfully
Data from page 119 has been added in the dataset successfully
Data from page 120 has been added in the dataset successfully
Data from page 121 has been added in the dataset successfully
Data from page 122 has been added in the dataset successfully
Data from page 123 has been added in the dataset successfully
Data from page 124 has been added in the dataset successfully
Data from page 125 has been added in the dataset successfully
Data from page 126 has been added in the dataset successfully
Data from page 127 has been added in the dataset successfully
Data from page 128 has been added in the dataset successfully
Data from page 129 has been added in the dataset successfully
Data from page 130 has been added in the dataset successfully
Data from page 131 has been added in the dataset successfully
Data from page 132 has been added in the dataset successfully
Data from page 133 has been added in the dataset successfully
Data from page 134 has been added in the dataset successfully
Data from page 135 has been added in the dataset successfully
Data from page 136 has been added in the dataset successfully
Data from page 137 has been added in the dataset successfully
Data from page 138 has been added in the dataset successfully
Data from page 139 has been added in the dataset successfully
Data from page 140 has been added in the dataset successfully
Data from page 141 has been added in the dataset successfully
Data from page 142 has been added in the dataset successfully
Data from page 143 has been added in the dataset successfully
Data from page 144 has been added in the dataset successfully
Data from page 145 has been added in the dataset successfully
Data from page 146 has been added in the dataset successfully
Data from page 147 has been added in the dataset successfully
Data from page 148 has been added in the dataset successfully
Data from page 149 has been added in the dataset successfully
Data from page 150 has been added in the dataset successfully
Data from page 151 has been added in the dataset successfully
Data from page 152 has been added in the dataset successfully
Data from page 153 has been added in the dataset successfully
Data from page 154 has been added in the dataset successfully
Data from page 155 has been added in the dataset successfully
Data from page 156 has been added in the dataset successfully
Data from page 157 has been added in the dataset successfully
Data from page 158 has been added in the dataset successfully
Data from page 159 has been added in the dataset successfully
Data from page 160 has been added in the dataset successfully
Data from page 161 has been added in the dataset successfully
Data from page 162 has been added in the dataset successfully
Data from page 163 has been added in the dataset successfully
Data from page 164 has been added in the dataset successfully
Data from page 165 has been added in the dataset successfully
Data from page 166 has been added in the dataset successfully
Data from page 167 has been added in the dataset successfully
Data from page 168 has been added in the dataset successfully
Data from page 169 has been added in the dataset successfully
Data from page 170 has been added in the dataset successfully
Data from page 171 has been added in the dataset successfully
Data from page 172 has been added in the dataset successfully
Data from page 173 has been added in the dataset successfully
Data from page 174 has been added in the dataset successfully
Data from page 175 has been added in the dataset successfully
Data from page 176 has been added in the dataset successfully
Data from page 177 has been added in the dataset successfully
Data from page 178 has been added in the dataset successfully
Data from page 179 has been added in the dataset successfully
Data from page 180 has been added in the dataset successfully
Data from page 181 has been added in the dataset successfully
Data from page 182 has been added in the dataset successfully
Data from page 183 has been added in the dataset successfully
Data from page 184 has been added in the dataset successfully
Data from page 185 has been added in the dataset successfully
Data from page 186 has been added in the dataset successfully
Data from page 187 has been added in the dataset successfully
Data from page 188 has been added in the dataset successfully
Data from page 189 has been added in the dataset successfully
Data from page 190 has been added in the dataset successfully
Data from page 191 has been added in the dataset successfully
Data from page 192 has been added in the dataset successfully
Data from page 193 has been added in the dataset successfully
Data from page 194 has been added in the dataset successfully
Data from page 195 has been added in the dataset successfully
Data from page 196 has been added in the dataset successfully
Data from page 197 has been added in the dataset successfully
Data from page 198 has been added in the dataset successfully
Data from page 199 has been added in the dataset successfully
Data from page 200 has been added in the dataset successfully
Data from page 201 has been added in the dataset successfully
Data from page 202 has been added in the dataset successfully
Data from page 203 has been added in the dataset successfully
Data from page 204 has been added in the dataset successfully
Data from page 205 has been added in the dataset successfully
Data from page 206 has been added in the dataset successfully
Data from page 207 has been added in the dataset successfully
Data from page 208 has been added in the dataset successfully
Data from page 209 has been added in the dataset successfully
Data from page 210 has been added in the dataset successfully
Data from page 211 has been added in the dataset successfully
Data from page 212 has been added in the dataset successfully
Data from page 213 has been added in the dataset successfully
Data from page 214 has been added in the dataset successfully
Data from page 215 has been added in the dataset successfully
Data from page 216 has been added in the dataset successfully
Data from page 217 has been added in the dataset successfully
Data from page 218 has been added in the dataset successfully
Data from page 219 has been added in the dataset successfully
Data from page 220 has been added in the dataset successfully
Data from page 221 has been added in the dataset successfully
Data from page 222 has been added in the dataset successfully
Data from page 223 has been added in the dataset successfully
Data from page 224 has been added in the dataset successfully
Data from page 225 has been added in the dataset successfully
Data from page 226 has been added in the dataset successfully
Data from page 227 has been added in the dataset successfully
Data from page 228 has been added in the dataset successfully
Data from page 229 has been added in the dataset successfully
Data from page 230 has been added in the dataset successfully
Data from page 231 has been added in the dataset successfully
Data from page 232 has been added in the dataset successfully
Data from page 233 has been added in the dataset successfully
Data from page 234 has been added in the dataset successfully
Data from page 235 has been added in the dataset successfully
Data from page 236 has been added in the dataset successfully
Data from page 237 has been added in the dataset successfully
Data from page 238 has been added in the dataset successfully
Data from page 239 has been added in the dataset successfully
Data from page 240 has been added in the dataset successfully
Data from page 241 has been added in the dataset successfully
Data from page 242 has been added in the dataset successfully
Data from page 243 has been added in the dataset successfully
Data from page 244 has been added in the dataset successfully
Data from page 245 has been added in the dataset successfully
Data from page 246 has been added in the dataset successfully
Data from page 247 has been added in the dataset successfully
Data from page 248 has been added in the dataset successfully
Data from page 249 has been added in the dataset successfully
Data from page 250 has been added in the dataset successfully
Data from page 251 has been added in the dataset successfully
Data from page 252 has been added in the dataset successfully
Data from page 253 has been added in the dataset successfully
Data from page 254 has been added in the dataset successfully
Data from page 255 has been added in the dataset successfully
Data from page 256 has been added in the dataset successfully
Data from page 257 has been added in the dataset successfully
Data from page 258 has been added in the dataset successfully
Data from page 259 has been added in the dataset successfully
Data from page 260 has been added in the dataset successfully
Data from page 261 has been added in the dataset successfully
Data from page 262 has been added in the dataset successfully
Data from page 263 has been added in the dataset successfully
Data from page 264 has been added in the dataset successfully
Data from page 265 has been added in the dataset successfully
Data from page 266 has been added in the dataset successfully
Data from page 267 has been added in the dataset successfully
Data from page 268 has been added in the dataset successfully
Data from page 269 has been added in the dataset successfully
Data from page 270 has been added in the dataset successfully
Data from page 271 has been added in the dataset successfully
Data from page 272 has been added in the dataset successfully
Data from page 273 has been added in the dataset successfully
Data from page 274 has been added in the dataset successfully
Data from page 275 has been added in the dataset successfully
Data from page 276 has been added in the dataset successfully
Data from page 277 has been added in the dataset successfully
Data from page 278 has been added in the dataset successfully
Data from page 279 has been added in the dataset successfully
Data from page 280 has been added in the dataset successfully
Data from page 281 has been added in the dataset successfully
Data from page 282 has been added in the dataset successfully
Data from page 283 has been added in the dataset successfully
Data from page 284 has been added in the dataset successfully
Data from page 285 has been added in the dataset successfully
Data from page 286 has been added in the dataset successfully
Data from page 287 has been added in the dataset successfully
Data from page 288 has been added in the dataset successfully
Data from page 289 has been added in the dataset successfully
Data from page 290 has been added in the dataset successfully
Data from page 291 has been added in the dataset successfully
Data from page 292 has been added in the dataset successfully
Data from page 293 has been added in the dataset successfully
Data from page 294 has been added in the dataset successfully
Data from page 295 has been added in the dataset successfully
Data from page 296 has been added in the dataset successfully
Data from page 297 has been added in the dataset successfully
Data from page 298 has been added in the dataset successfully
Data from page 299 has been added in the dataset successfully
Data from page 300 has been added in the dataset successfully
Data from page 301 has been added in the dataset successfully
Data from page 302 has been added in the dataset successfully
Data from page 303 has been added in the dataset successfully
Data from page 304 has been added in the dataset successfully
Data from page 305 has been added in the dataset successfully
Data from page 306 has been added in the dataset successfully
Data from page 307 has been added in the dataset successfully
Data from page 308 has been added in the dataset successfully
Data from page 309 has been added in the dataset successfully
Data from page 310 has been added in the dataset successfully
Data from page 311 has been added in the dataset successfully
Data from page 312 has been added in the dataset successfully
Data from page 313 has been added in the dataset successfully
Data from page 314 has been added in the dataset successfully
Data from page 315 has been added in the dataset successfully
Data from page 316 has been added in the dataset successfully
Data from page 317 has been added in the dataset successfully
Data from page 318 has been added in the dataset successfully
Data from page 319 has been added in the dataset successfully
Data from page 320 has been added in the dataset successfully
Data from page 321 has been added in the dataset successfully
Data from page 322 has been added in the dataset successfully
Data from page 323 has been added in the dataset successfully
Data from page 324 has been added in the dataset successfully

In [3]:
final.shape

(10000, 7)

In [9]:
final.sample(50)

,Name,Rating,Reviews,Company_Type,Headquarters,Highly Rated,Most Critically Rated
8602,CNS Comnet,4.1,(128),BPO,Gurgaon / Gurugram +4 other locations,"[Company Culture, Work Life Balance, Work Sati...",[Job Security]
763,TEKsystems,3.1,(1.4k),IT Services & Consulting,Bengaluru +18 other locations,[nan],"[Promotions, Job Security, Skill Development]"
3026,Pranav Vikas India Private Limited,3.7,(364),Automobile,Faridabad +16 other locations,[nan],"[Job Security, Promotions]"
8169,DigiVersal Consultants,2.7,(136),Internet,Noida +5 other locations,[nan],"[Job Security, Promotions, Work Life Balance]"
5664,Nutanix,3.5,(197),Software Product,Bengaluru +6 other locations,[nan],"[Promotions, Job Security, Work Satisfaction]"
2841,Evoke Technologies,3.7,(387),IT Services & Consulting,Hyderabad +4 other locations,[nan],"[Promotions, Job Security, Salary]"
1694,Mount Litera Zee School,3.7,(635),Education & Training,Bengaluru +125 other locations,[nan],"[Promotions, Job Security, Salary]"
2486,Tata Steel Downstream Products,3.7,(439),Iron & Steel,Jamshedpur +37 other locations,[Job Security],"[Promotions, Salary]"
2535,Calsoft,2.7,(431),IT Services & Consulting,Pune +7 other locations,[nan],"[Promotions, Job Security, Company Culture]"
6167,Sistema Shyam Teleservices,4.9,(180),Telecom,Gurugram +42 other locations,"[Work Satisfaction, Salary, Company Culture]",[nan]
2422,Prism Cement,4.0,(452),Building Material,Satna +77 other locations,"[Work Life Balance, Job Security, Company Cult...",[nan]
5277,Moody's,3.9,(211),Analytics & KPO,Bengaluru +7 other locations,"[Work Life Balance, Company Culture, Salary]",[Promotions]
6439,Gsa Industries,4.0,(173),Automobile,Patiala +6 other locations,"[Skill Development, Salary, Work Life Balance]",[nan]
9168,Amco Batteries,4.3,(120),Auto Components,Chennai +23 other locations,"[Work Life Balance, Company Culture, Work Sati...",[nan]
6945,Amphenol Omniconnect - India,3.9,(161),Electronics Manufacturing,Chennai +4 other locations,"[Work Life Balance, Work Satisfaction, Job Sec...","[Promotions, Salary]"
8132,Solulab inc,3.2,(137),IT Services & Consulting,Ahmedabad +3 other locations,[nan],"[Job Security, Promotions, Salary]"
2337,Visaka Industries,3.8,(469),Building Material,Hyderabad +59 other locations,[Work Life Balance],"[Promotions, Skill Development]"
8133,Futuresoft Solutions,3.1,(137),IT Services & Consulting,New Delhi +20 other locations,[nan],"[Promotions, Salary, Company Culture]"
6751,St. Mary's School,3.9,(165),Education & Training,New Delhi +64 other locations,"[Work Satisfaction, Skill Development]",[Promotions]
5038,SRR Projects,4.1,(220),Engineering & Construction,Hyderabad +24 other locations,"[Salary, Company Culture, Work Satisfaction]",[nan]
7771,Neverskip,3.7,(143),Education & Training,Chennai +27 other locations,[nan],"[Promotions, Salary]"
8689,OCS Services,4.4,(127),Oil & Gas,Mumbai +28 other locations,"[Company Culture, Work Life Balance, Work Sati...",[nan]
2009,Regalix,2.7,(540),Marketing & Advertising,Hyderabad +7 other locations,[nan],"[Promotions, Job Security, Company Culture]"
2818,Shree Baidyanath Ayurved Bhawan,3.9,(391),Pharma,Kolkata +44 other locations,"[Work Life Balance, Job Security]",[Promotions]
7200,Bhartiya International,3.5,(155),Fashion & Textile,Bengaluru +12 other locations,[nan],"[Promotions, Company Culture, Work Satisfaction]"
8749,Alexis Global,3.8,(126),Logistics,New Delhi +26 other locations,"[Work Life Balance, Skill Development]",[Promotions]
814,Decathlon,3.7,(1.3k),Retail,Bengaluru +71 other locations,"[Job Security, Skill Development, Company Cult...","[Promotions, Work Life Balance, Salary]"
5457,Haldiram's Prabhuji,2.8,(204),FMCG,Kolkata +42 other locations,[nan],"[Promotions, Job Security, Company Culture]"
2610,ABCI Infrastructures,3.4,(421),Engineering & Construction,Bengaluru +51 other locations,[nan],"[Promotions, Company Culture, Work Satisfaction]"
5769,Webasto Roofsystems India,3.9,(194),Automobile,Pune +9 other locations,"[Company Culture, Work Life Balance, Skill Dev...",[Promotions]
8442,Secure Network Solutions,4.4,(131),IT Services & Consulting,Chennai +10 other locations,"[Skill Development, Work Satisfaction, Job Sec...",[nan]
743,Xiaomi,3.8,(1.4k),Consumer Electronics & Appliances,Bengaluru +213 other locations,[nan],"[Promotions, Job Security]"
6878,Ccl Products,4.1,(161),Beverage,Hyderabad +26 other locations,"[Job Security, Company Culture, Work Life Bala...",[nan]
273,Marpu Foundation,4.9,(3.1k),Non-Profit,Hyderabad +61 other locations,"[Company Culture, Work Life Balance, Work Sati...",[nan]
3574,Alicon Castalloy,3.4,(310),Auto Components,Pune +12 other locations,[nan],"[Company Culture, Job Security, Work Life Bala..."
1495,Bikanervala,3.9,(714),FMCG,New Delhi +70 other locations,[Work Life Balance],[Promotions]
9755,Pentair Water India,3.7,(112),Industrial Machinery,Noida +10 other locations,[Work Life Balance],"[Promotions, Work Satisfaction, Job Security]"
2295,Keysight Technologies,3.8,(473),Electronics Manufacturing,Gurugram +12 other locations,"[Work Life Balance, Company Culture, Job Secur...","[Promotions, Salary, Skill Development]"
1927,Micromax Informatics,3.9,(566),Consumer Electronics & Appliances,New Delhi +118 other locations,[Work Life Balance],"[Promotions, Job Security]"
5895,Rimini Street,4.0,(189),IT Services & Consulting,Hyderabad +2 other locations,"[Work Life Balance, Company Culture, Salary]","[Promotions, Skill Development]"
1815,Blackberrys,3.7,(600),Fashion & Textile,Gurugram +92 other locations,[nan],"[Job Security, Promotions]"
6328,Pan Gulf Technologies,4.0,(175),Design,Mumbai +8 other locations,"[Company Culture, Job Security, Work Satisfact...",[Promotions]
8418,Planet EDU,3.3,(131),EdTech,Gurugram +23 other locations,[nan],"[Promotions, Salary, Job Security]"
7146,SOTI,3.1,(156),Software Product,Gurugram +9 other locations,[nan],"[Promotions, Salary, Company Culture]"
3076,Audi,3.7,(359),Automobile,New Delhi +55 other locations,[Work Life Balance],"[Promotions, Salary]"
7804,FANUC,3.2,(143),Industrial Automation,Bengaluru +8 other locations,[Job Security],"[Work Life Balance, Work Satisfaction, Promoti..."
394,RMSI,3.5,(2.3k),IT Services & Consulting,Hyderabad +24 other locations,[nan],"[Promotions, Salary, Skill Development]"
1968,FiveS Digital,3.3,(552),BPO,Jamshedpur +27 other locations,[nan],"[Salary, Promotions, Job Security]"
5178,Ajax Engineering,4.0,(215),Engineering & Construction,Bengaluru +29 other locations,"[Work Life Balance, Company Culture]",[Promotions]
1853,Saudi Aramco,4.5,(587),Oil & Gas,Mumbai +38 other locations,"[Work Life Balance, Salary, Company Culture]",[nan]

In [ ]:
final.to_json('company_comparsion_dataset.json', orient='records')

In [15]:
import openpyxl
final.to_excel('company_comparsion_dataset.xlsx', index=False, engine='openpyxl')